// <auto-generated />
namespace AfroNFTs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class isAvel_theNFTs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isAvel_theNFTs));
        
        string IMigrationMetadata.Id
        {
            get { return "202210201438007_isAvel_theNFTs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
