// <auto-generated />
namespace AfroNFTs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class isAvel_theNFTs1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isAvel_theNFTs1));
        
        string IMigrationMetadata.Id
        {
            get { return "202210201444491_isAvel_theNFTs1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
