// <auto-generated />
namespace AfroNFTs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Admin_NFTsClass_NormalUser_Page : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Admin_NFTsClass_NormalUser_Page));
        
        string IMigrationMetadata.Id
        {
            get { return "202210100810111_Admin_NFTsClass_NormalUser_Page"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
